/* <copyright file="IVersionInfo.cs" company="Xeno Innovations, Inc.">
 * Copyright (c) Xeno Innovations, Inc. All rights reserved.
 * </copyright>
 *
 * Date:    2019-9-28
 * Author:  Damian Suess
 * File:    IVersionInfo.cs
 * Description:
 *  Version information interface
 *
 * <Auto-Generated>This is here so CodeMaid doesn't reorganize this document</Auto-Generated>
 */

using System;

namespace LiteMigrator.DataObjects
{
  public interface IVersionInfo
  {
    long VersionNumber { get; set; }

    DateTime AppliedDttm { get; set; }

    string Description { get; set; }
  }
}
