/* Copyright Xeno Innovations, Inc. 2019
 * Date:    2019-9-28
 * Author:  Damian Suess
 * File:    IVersionInfo.cs
 * Description:
 *  Version information interface
 *
 * <Auto-Generated>This is here so CodeMaid doesn't reorganize this document</Auto-Generated>
 */

using System;

namespace Xeno.LiteMigrator.DataObjects
{
  public interface IVersionInfo
  {
    long VersionNumber { get; set; }

    DateTime AppliedDttm { get; set; }

    string Description { get; set; }
  }
}
