/* <copyright file="VersionInfo.cs" company="Xeno Innovations, Inc.">
 * Copyright (c) Xeno Innovations, Inc. All rights reserved.
 * </copyright>
 *
 * Date:    2019-9-24
 * Author:  Damian Suess
 * File:    VersionInfo.cs
 * Description:
 *  LiteMigrator Version Information Table
 *
 * <Auto-Generated>This is here so CodeMaid doesn't reorganize this document</Auto-Generated>
 */

using System;
using SQLite;

namespace LiteMigrator.DataObjects;

[Table("VersionInfo")]
public class VersionInfo : IVersionInfo
{
  [PrimaryKey]
  [AutoIncrement]
  public int VersionId { get; set; }

  public long VersionNumber { get; set; }

  public DateTime AppliedDttm { get; set; }

  public string Description { get; set; }
}
